cursor #9dcfd8
cursor_text_color #0e474f

foreground            #dde7e9
background            #0a0f10
selection_foreground  #2c4448
selection_background  #bfd9de
url_color             #9dcfd8

color0   #0a0f10
color1   #f86f9e
color2   #6cd876
color3   #fff572
color4   #89c2cd
color5   #265961
color6   #9dcfd8
color7   #d5e0e2
color8   #383f40
color9   #ff9fc0
color10  #a5ffae
color11  #fff8a5
color12  #b6e5ed
color13  #cef7ff
color14  #dffaff
color15  #f8feff
