password00: ENC[AES256_GCM,data:RcoHaaaOBAEdIomf,iv:yP+xN6Bygwg1QGT+BBEIqgkNMG+VIxtkCk2yJewReRY=,tag:ku8D2KCbS7tgb8zb/WKjUg==,type:str]
tailscale_key: ENC[AES256_GCM,data:WRsftDgT4uoPFthEuPUOp+CLoUN970lA6NXi5Kt4Mo5ixL4MZjJXh/XAKnnR5kP54+3s0FRCp+/qHur8tw==,iv:G4Tkp+JpF38QAwRwhDkr+EFyi8f9lWKUB3yJyYhCsH4=,tag:w5fyT112nKl+DgTrWZWM/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdkVDWnF0ZldyY3FZektO
            eGxxSDZlaFNjK292S0MwQ0FFY3VWSUYzMkZjClRDS2pQekhOaW8vaUdGMTdmSlJH
            VkJ4UnBQZmJ6RkozaFZNQ3FNMDI1cEUKLS0tIHUyTDFPK3lBR1Fya3NxRW8rODNx
            VGpJWndvM2g0ZTdZR1BTdExINnViWm8Ktzqk3VLsJJXL0EnOhNQL7yGYD0TPUSd3
            z2s+XGh7izbuW61q0v24a6J8ltbFYDK/cQ40gNHAq6KxTS7P8Z7a/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suusxjc3k3tc82n45sygzuwfx7uh95gt0c3g6la959260th9tsnq9j6jxt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNDh4ell1YUxudGwvMGor
            MjFFUkdUNHVaMlVmRWpMWnh6eElZYzMwR3lvCnJMVmYyTkozdHl0WTU5RFQzdllX
            eE96VjQ1UHRsUnRDaVhOMWd2R3N0TjAKLS0tIGNOWThYYUJjNjIrUVZEaEFwNjZo
            UU5kQ1NuME9vNFFQVFpiZ3JxbzE2NFkKp1QRheMmXocbxmpoqQR792rUdikf/sWm
            GSoi0IG9I8ERjKxa60ghjR21QW6BSzF5pgKfqnk8CqpqKHiRoLCG8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uvfvuvj0k4damar8t6urt4w9dmehf06xhz5xp2p9jj6vy8vdlyaqcenktq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVjNBRmRMZ2gxc1I4T3ZY
            eDA2Ujk2a0lHYzRmMGdYcU5OVUpucSt6amhNCmRKTlgvOVN2aHdnWlJvSk1XSXBD
            VGhnR1ZHSDV3bWpQMlREN0R3cCt2MWsKLS0tIDZxdVhxVE9JU3ZpL3BZTjg2YlpV
            MHlxdjZ2RXlYTjhSRFpDbm5OaUhHTkkKowIjwklniUPfdDTMLXBzjDbidMSSnfxW
            2dRKfcuM2V4opiNCc4sqvhwwBgt4vTEIO/xIOJGSxmjvKC9xJhtQEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18j8metr79q9yzqy7xg3fn39hs5c0f4xgpr5wsca0fxv2t6c29acst5sl7l
    lastmodified: "2026-02-22T11:44:58Z"
    mac: ENC[AES256_GCM,data:Qelz9o+n4/sJWErEd/QpqDPrAcdPCss67K8XRTLePFLCkMExY4vXDnzNK1N2c+umKuU+wYxRm7drmjL0E0SHrxwr11dlUaUfA+C8epRJbACNwa+tngGxXguDyih1GmaxGP+yQm7bRrINbNqFXC9DKBCb7Pi9Jqh98zysCNvzwFk=,iv:1jD48RdoJX3dNZ12lYXtfSsu8E5rZ+iQu5h/pecLHmo=,tag:AWo9OZvVm/w0ZoEZDY8vcg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
