password00: ENC[AES256_GCM,data:RcoHaaaOBAEdIomf,iv:yP+xN6Bygwg1QGT+BBEIqgkNMG+VIxtkCk2yJewReRY=,tag:ku8D2KCbS7tgb8zb/WKjUg==,type:str]
password01: ENC[AES256_GCM,data:bL+49hHZBQ==,iv:Vko1GGR6sUUpqXbwxxCk2J0JblpOYXMQXxwclC7MYQk=,tag:gLqY8Bm4BfczJ/sPKWGSaw==,type:str]
tailscale_key: ENC[AES256_GCM,data:1zT6X6am8hrdtUOcPkVdfpkFhbl0by6l/T0KPvUfRz6n8erVDtvuwDOJlKI1OIUblb/blA834H2332YjcA==,iv:1xrjnt8dCF0FbewmNzgrXFW6XmzqrqOo5MgLJ226FMU=,tag:LdV3pqCvDRIloc8TPpBJuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZFFOdkxRd05wMU5wem5Z
            VkloWlQyalVSbkhaK1VTWmFTOG1IajJLYldzCnZxS3RvWHpOVmJKNUg4T2hJNFNp
            U1J1K3UwbEV3OXFqazB6bE5jY2R4RUkKLS0tIHFEaEZyRFYrTWMyZlJkZnI5SWFM
            dnR1ZlFndUs2ekxPOVVFdUVGQzRCY2MKN4+s1trDDVBwYSgqKUCfl4T62VGDgP+w
            1wcXGhdVI5DPVUQslRBIA12WBJWAJpmH+3rFHar39KtdpruG3BYAjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suusxjc3k3tc82n45sygzuwfx7uh95gt0c3g6la959260th9tsnq9j6jxt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaGRjcVhicGdJbFMxYUNL
            UXcyK0sremNaa0I2UXBkazVlQzdURjI4WWdVCkZ4K2hQTUJmNHhjYkRDRlJWMGJZ
            ZDRjNDdIZVhJcGtSR3JMQ3ZBQWVQL3cKLS0tIGdTenZxZGNmaXhuZjBSNk9HeDVD
            ZkxpVXlQOVgrUUtwbkJ2T3VrNDhqM3MKmsBbzYQo+AhqmPYFSxE/etlhDDUZS8u4
            Liie2lMGvITMvIDvCG6keE8SjqhzSqun34iGRzJBy9ckRwlVjdeQ1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uvfvuvj0k4damar8t6urt4w9dmehf06xhz5xp2p9jj6vy8vdlyaqcenktq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dnZOV3NRa0pJczhjcitm
            NTZyNk16b2hrNEhCU1VweDhpTC9UR01vTm1rCkFMZjNMdFJ3RmRGelVUbDVxdHJV
            aXJpdFpwWXF0ZTNMb0M3V21QTklldlkKLS0tIE90a2xQSm1GR0VTdG9hM05oVHQx
            dW04VlpIWlMvUjJDRE85QlRwZ0w2Yk0KzFdAovvyTBD2jNMzeQGdKnadrHCIscNu
            Zyt7gcdWouq42l8kEe7mZsgx7aOTRSfGONRp8357xcIsttwlU+76vA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18j8metr79q9yzqy7xg3fn39hs5c0f4xgpr5wsca0fxv2t6c29acst5sl7l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQmVGQVE1THZ6ZW40UG1C
            VnpHRDZ1eFFzTVZueDVaajMzQlF6UHBiSURrCkhZRzZxZ3N3SmpDZEZ5bDRxN0cr
            MVpubUowYklmQ2ROOWlHWnhzQ2pkNFkKLS0tIFR4bTVwUGJDMGpXVHR2K3UzRFpU
            TXEzMWRRekRwU2MvQ2ZCdjAvN1M5YkEKQbGI4nD0oE13RB/ZwH7XgEtQmLP+fFWh
            ldqiqvvv5qsqDpx/ZdtPdLK/1GQK2xKan2SNG9YCJcZAgQwncu+wyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hr3udprcluyhnfmc872esrezs6uxzmk92lad9mnlzlmph6e6vusqn8cctz
    lastmodified: "2026-07-20T16:54:11Z"
    mac: ENC[AES256_GCM,data:++nKkYNGXIIrSTto7g1yKjLJeKpAp38SqfyHO272PeqSsclv9jXdQqOhKZRbszl7VzJ9Fsyi2p97vdjmWd8DDqwJUuG0HiyttpqssPKO378zMPac+lhRfgdp43t0UcjSWYFFLCnlPw9884XvDu3wdxnGWnnm72ioLdyCNtAxjtU=,iv:xHw4fWa3VoGTmBTulvyPI10QFDudR1OaA4GMpk7uuBk=,tag:hm09QzSZ8exmllCTnOepYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
