password00: ENC[AES256_GCM,data:RcoHaaaOBAEdIomf,iv:yP+xN6Bygwg1QGT+BBEIqgkNMG+VIxtkCk2yJewReRY=,tag:ku8D2KCbS7tgb8zb/WKjUg==,type:str]
tailscale_key: ENC[AES256_GCM,data:WRsftDgT4uoPFthEuPUOp+CLoUN970lA6NXi5Kt4Mo5ixL4MZjJXh/XAKnnR5kP54+3s0FRCp+/qHur8tw==,iv:G4Tkp+JpF38QAwRwhDkr+EFyi8f9lWKUB3yJyYhCsH4=,tag:w5fyT112nKl+DgTrWZWM/Q==,type:str]
sops:
    age:
        - recipient: age1suusxjc3k3tc82n45sygzuwfx7uh95gt0c3g6la959260th9tsnq9j6jxt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkU1l1SERUQjB4Sjd3cWV2
            M0w1WER5STlUY0NoaGI3a2FwUnVSVFE1Z1YwCnc3ZlJCSkd1S3grbUJ1ZGJQcDJz
            Wm8zc2ZIR2ZrL3lObXdUUi9uNldQUlkKLS0tIEZRQkRUVGYrb3l6S0NDc3JoV2pq
            QWhuVWxFSmlvQjI1SEM5UDZCMEJnT28KIw3BXT6FdVgeWWx3h2UoSmEmzd7anluO
            xeHeuPvCchkWFsQ70faX/GGS3dyaClNHHwc6mY4Uo4UEAix6rK6kjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uvfvuvj0k4damar8t6urt4w9dmehf06xhz5xp2p9jj6vy8vdlyaqcenktq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QWNKMDZQY1oyZmVScHF6
            NElKKzYrT0ZQNUt4SE42cXZoNmVFaGhIN3hFCjVRUFY1eUJXa3RiSkwvZnJMZTVx
            RmtCY093MithM1RVWHVsaHZ3N2ZOT1UKLS0tIDlBZmpqSUptZktQUERTSFVGRWlt
            QVRhV3EramQwcEFQWFZ0WGFibXdtT00KyxPUyup6LmFbWH8pHCiDrBktHH1SyuYN
            EylYqz7ytjw0I0B83St0QTZR5gfiSAUpQ1Fa6rAjY+rQRim5cDSTBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T11:44:58Z"
    mac: ENC[AES256_GCM,data:Qelz9o+n4/sJWErEd/QpqDPrAcdPCss67K8XRTLePFLCkMExY4vXDnzNK1N2c+umKuU+wYxRm7drmjL0E0SHrxwr11dlUaUfA+C8epRJbACNwa+tngGxXguDyih1GmaxGP+yQm7bRrINbNqFXC9DKBCb7Pi9Jqh98zysCNvzwFk=,iv:1jD48RdoJX3dNZ12lYXtfSsu8E5rZ+iQu5h/pecLHmo=,tag:AWo9OZvVm/w0ZoEZDY8vcg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
